### PR TITLE
Include an upload's full file URL in the JSON and XML responses

### PR DESCRIPTION
**Pull request by laserlemon**

### CODE REVIEW

**Comment by emilford** [comment]
:eyes: :white_check_mark: :thumbsup:

**Comment by laserlemon** [comment]
@ersatzryan :shipit: :pray:

**Comment by ersatzryan** [comment]
are we just storing the uploads on the filesystem currently? One of the things we wanted was easy heroku setup.

**Comment by laserlemon** [comment]
For now, yes, on the filesystem. My first goal is to allow this to be used as a behind-the-firewall installation (no Heroku, no S3). Filesystem storage works just fine for that case. Later, I'd like it to use S3 if credentials are set in Figaro.

**Pull request merged**
