### PR TITLE
Use pry-rails

### PR DESCRIPTION
**Pull request by danielmorrison**
Instead of just vanilla pry

### CODE REVIEW

**Comment by laserlemon** [comment]
What kind of cool stuff does this give us?

**Comment by danielmorrison** [comment]
Main thing is `rails console` uses pry by default.

**Comment by laserlemon** [comment]
:recycle: :pray:

**Comment by laserlemon** [comment]
Thank you!

**Comment by ersatzryan** [comment]
@laserlemon you would know if you ever watched or read anything I sent to you!!!

**Comment by laserlemon** [comment]
Oops!

**Pull request merged**
