### PR TITLE
Add the /account endpoint

### PR DESCRIPTION
**Pull request by laserlemon**

### CODE REVIEW

**Comment by ersatzryan** [comment]
how would this implementation change if we started hosting open chats for people?

**Comment by ersatzryan** [comment]
we don't have to solve that now and it might just be a lot would change, so it is too much to even consider now. I just want to start you considering that idea as we make decisions

**Comment by laserlemon** [comment]
Absolutely. Yes it would change quite a bit. It's not really on my radar at this point.

**Comment by ersatzryan** [comment]
That is ok and understandable, as it probably shouldn't be. However, we might want to keep it in mind when we make decisions like accounts. I could see certain installs (_hint_ _hint_) wanting separate accounts for different teams

**Comment by laserlemon** [comment]
Good point.

**Pull request merged**
